version: '3'
services:
    db:
        image: mysql
        ports:
            - "16306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: my_project
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - ~/mysql_myproject:/var/lib/mysql
    php:
        image: sherlockode/symfony_php-fpm:8.1
        expose:
            - "9000"
        volumes:
            - .:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/log
    nginx:
        image: sherlockode/symfony_nginx
        ports:
            - "16080:80"
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
